# Generated by Django 2.2.6 on 2020-01-17 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_auto_20190514_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=200)),
                ('text', models.TextField(blank=True, null=True)),
                ('addons', models.ManyToManyField(related_name='stats', to='projekt47.Addon')),
            ],
        ),
        migrations.CreateModel(
            name='Projekt47User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(blank=True, max_length=200, null=True)),
                ('telebot_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projekt47_user', to='core.TelebotUser')),
            ],
        ),
        migrations.CreateModel(
            name='CharStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt47.Character')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt47.Stat')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='projekt47.Game'),
        ),
        migrations.AddField(
            model_name='character',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projekt47.Projekt47User'),
        ),
        migrations.AddField(
            model_name='character',
            name='stats',
            field=models.ManyToManyField(through='projekt47.CharStat', to='projekt47.Stat'),
        ),
        migrations.AddField(
            model_name='addon',
            name='games',
            field=models.ManyToManyField(blank=True, null=True, related_name='addons', to='projekt47.Game'),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('formula', models.CharField(blank=True, max_length=200, null=True)),
                ('answer', models.CharField(blank=True, max_length=300, null=True)),
                ('addons', models.ManyToManyField(related_name='actions', to='projekt47.Addon')),
                ('stats', models.ManyToManyField(blank=True, null=True, related_name='actions', to='projekt47.Stat')),
            ],
        ),
    ]
