# Generated by Django 2.2.6 on 2020-01-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt47', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addon',
            name='games',
        ),
        migrations.AddField(
            model_name='game',
            name='addons',
            field=models.ManyToManyField(blank=True, null=True, related_name='games', to='projekt47.Addon'),
        ),
    ]
